// Mocks generated by Mockito 5.4.6 from annotations
// in src/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:src/models/api_enums.dart' as _i15;
import 'package:src/models/auth_models.dart' as _i2;
import 'package:src/models/cart_models.dart' as _i5;
import 'package:src/models/catalog_models.dart' as _i4;
import 'package:src/models/order_models.dart' as _i6;
import 'package:src/models/review_models.dart' as _i7;
import 'package:src/models/user_models.dart' as _i3;
import 'package:src/repositories/book_repository.dart' as _i11;
import 'package:src/services/auth_service.dart' as _i8;
import 'package:src/services/book_service.dart' as _i10;
import 'package:src/services/cart_service.dart' as _i12;
import 'package:src/services/order_service.dart' as _i14;
import 'package:src/services/review_service.dart' as _i16;
import 'package:src/services/wishlist_service.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_1 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookResponse_2 extends _i1.SmartFake implements _i4.BookResponse {
  _FakeBookResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartResponse_3 extends _i1.SmartFake implements _i5.CartResponse {
  _FakeCartResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderResponse_4 extends _i1.SmartFake implements _i6.OrderResponse {
  _FakeOrderResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayOsCheckoutResponse_5 extends _i1.SmartFake
    implements _i6.PayOsCheckoutResponse {
  _FakePayOsCheckoutResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReviewResponse_6 extends _i1.SmartFake
    implements _i7.ReviewResponse {
  _FakeReviewResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.AuthResponse> register({
    required String? email,
    required String? password,
    required String? fullName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #fullName: fullName,
            }),
            returnValue: _i9.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #password: password,
                  #fullName: fullName,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.AuthResponse>);

  @override
  _i9.Future<_i2.AuthResponse> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i9.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.AuthResponse>);

  @override
  _i9.Future<_i2.AuthResponse> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i9.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i9.Future<_i2.AuthResponse>);

  @override
  _i9.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.UserResponse> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i9.Future<_i3.UserResponse>.value(
              _FakeUserResponse_1(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i9.Future<_i3.UserResponse>);
}

/// A class which mocks [BookService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookService extends _i1.Mock implements _i10.BookService {
  MockBookService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i4.BookResponse>> getBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getBooks, []),
            returnValue: _i9.Future<List<_i4.BookResponse>>.value(
              <_i4.BookResponse>[],
            ),
          )
          as _i9.Future<List<_i4.BookResponse>>);

  @override
  _i9.Future<_i4.BookResponse> getBook(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBook, [id]),
            returnValue: _i9.Future<_i4.BookResponse>.value(
              _FakeBookResponse_2(this, Invocation.method(#getBook, [id])),
            ),
          )
          as _i9.Future<_i4.BookResponse>);

  @override
  _i9.Future<_i4.BookResponse> createBook(_i4.BookRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createBook, [request]),
            returnValue: _i9.Future<_i4.BookResponse>.value(
              _FakeBookResponse_2(
                this,
                Invocation.method(#createBook, [request]),
              ),
            ),
          )
          as _i9.Future<_i4.BookResponse>);

  @override
  _i9.Future<void> updateBook(int? id, _i4.BookRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#updateBook, [id, request]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteBook(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBook, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i11.BookRepository {
  MockBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i4.BookResponse>> getBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getBooks, []),
            returnValue: _i9.Future<List<_i4.BookResponse>>.value(
              <_i4.BookResponse>[],
            ),
          )
          as _i9.Future<List<_i4.BookResponse>>);

  @override
  _i9.Future<List<_i4.BookResponse>> searchBooks(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#searchBooks, [keyword]),
            returnValue: _i9.Future<List<_i4.BookResponse>>.value(
              <_i4.BookResponse>[],
            ),
          )
          as _i9.Future<List<_i4.BookResponse>>);

  @override
  _i9.Future<List<_i4.BookResponse>> filterByCategory(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#filterByCategory, [categoryId]),
            returnValue: _i9.Future<List<_i4.BookResponse>>.value(
              <_i4.BookResponse>[],
            ),
          )
          as _i9.Future<List<_i4.BookResponse>>);
}

/// A class which mocks [CartService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartService extends _i1.Mock implements _i12.CartService {
  MockCartService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.CartResponse> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i9.Future<_i5.CartResponse>.value(
              _FakeCartResponse_3(this, Invocation.method(#getCart, [])),
            ),
          )
          as _i9.Future<_i5.CartResponse>);

  @override
  _i9.Future<_i5.CartResponse> addItem(_i5.CartItemRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [request]),
            returnValue: _i9.Future<_i5.CartResponse>.value(
              _FakeCartResponse_3(this, Invocation.method(#addItem, [request])),
            ),
          )
          as _i9.Future<_i5.CartResponse>);

  @override
  _i9.Future<void> updateItem(
    int? itemId,
    _i5.UpdateCartItemRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [itemId, request]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeItem(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [itemId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [WishlistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistService extends _i1.Mock implements _i13.WishlistService {
  MockWishlistService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i4.BookResponse>> getWishlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlist, []),
            returnValue: _i9.Future<List<_i4.BookResponse>>.value(
              <_i4.BookResponse>[],
            ),
          )
          as _i9.Future<List<_i4.BookResponse>>);

  @override
  _i9.Future<void> addToWishlist(int? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#addToWishlist, [bookId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeFromWishlist(int? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWishlist, [bookId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> checkWishlist(int? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#checkWishlist, [bookId]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}

/// A class which mocks [OrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderService extends _i1.Mock implements _i14.OrderService {
  MockOrderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i6.OrderResponse>> getOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, []),
            returnValue: _i9.Future<List<_i6.OrderResponse>>.value(
              <_i6.OrderResponse>[],
            ),
          )
          as _i9.Future<List<_i6.OrderResponse>>);

  @override
  _i9.Future<List<_i6.OrderResponse>> getMyOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getMyOrders, []),
            returnValue: _i9.Future<List<_i6.OrderResponse>>.value(
              <_i6.OrderResponse>[],
            ),
          )
          as _i9.Future<List<_i6.OrderResponse>>);

  @override
  _i9.Future<_i6.OrderResponse> getOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOrder, [id]),
            returnValue: _i9.Future<_i6.OrderResponse>.value(
              _FakeOrderResponse_4(this, Invocation.method(#getOrder, [id])),
            ),
          )
          as _i9.Future<_i6.OrderResponse>);

  @override
  _i9.Future<_i6.PayOsCheckoutResponse> createPayOsOrder(
    _i6.CreateOrderRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPayOsOrder, [request]),
            returnValue: _i9.Future<_i6.PayOsCheckoutResponse>.value(
              _FakePayOsCheckoutResponse_5(
                this,
                Invocation.method(#createPayOsOrder, [request]),
              ),
            ),
          )
          as _i9.Future<_i6.PayOsCheckoutResponse>);

  @override
  _i9.Future<void> updateStatus(int? id, _i15.OrderStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [id, status]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrder, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [ReviewService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewService extends _i1.Mock implements _i16.ReviewService {
  MockReviewService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i7.ReviewResponse>> getAllReviews() =>
      (super.noSuchMethod(
            Invocation.method(#getAllReviews, []),
            returnValue: _i9.Future<List<_i7.ReviewResponse>>.value(
              <_i7.ReviewResponse>[],
            ),
          )
          as _i9.Future<List<_i7.ReviewResponse>>);

  @override
  _i9.Future<List<_i7.ReviewResponse>> getReviewsByBook(int? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsByBook, [bookId]),
            returnValue: _i9.Future<List<_i7.ReviewResponse>>.value(
              <_i7.ReviewResponse>[],
            ),
          )
          as _i9.Future<List<_i7.ReviewResponse>>);

  @override
  _i9.Future<_i7.ReviewResponse> createReview(_i7.ReviewRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createReview, [request]),
            returnValue: _i9.Future<_i7.ReviewResponse>.value(
              _FakeReviewResponse_6(
                this,
                Invocation.method(#createReview, [request]),
              ),
            ),
          )
          as _i9.Future<_i7.ReviewResponse>);

  @override
  _i9.Future<void> updateReview(int? id, _i7.ReviewRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#updateReview, [id, request]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteReview(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReview, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
